- .pre-commit-config.yaml
- myskoda/__init__.py
- myskoda/authorization.py
- myskoda/cli.py
- myskoda/const.py
- myskoda/models/__init__.py
- myskoda/models/air_conditioning.py
- myskoda/models/charging.py
- myskoda/models/common.py
- myskoda/models/driving_range.py
- myskoda/models/health.py
- myskoda/models/info.py
- myskoda/models/maintenance.py
- myskoda/models/position.py
- myskoda/models/status.py
- myskoda/models/trip_statistics.py
- myskoda/rest_api.py
- pyproject.toml
* Enable (almost) all ruff rules, but disable the most obnoxious or incompatible ones.
I like to start with all rules enabled and then disable anything we agree are overly pedantic or unnecessary.
Fix any remaining findings in the code. Mostly line length and type annotations.
100% open for discussion.
* Add pre-commit config for ruff and fix ruff findings
> Code quality things

- myskoda/authorization.py
- myskoda/const.py
This should help dealing with https://github.com/skodaconnect/homeassistant-myskoda/issues/16
> Retry refreshing the access token on failure

- myskoda/models/maintenance.py
Fixes skodaconnect/homeassistant-myskoda#25
> Allow ServicePartner Contact fields to be missing

- myskoda/models/common.py
> Add missing "TRUNK_OPENED" for DoorLockedState

- myskoda/models/common.py
- tests/fixtures/superb/vehicle-status-doors-closed.json
- tests/fixtures/superb/vehicle-status-left-back-door-trunk-bonnet-opened.json
- tests/fixtures/superb/vehicle-status-right-front-door-opened.json
- tests/test_rest_api.py
Added test for vehicle status call based on the Superb iV responses.
Superb iV also reports OPENED state when any door is opened.
> Add doors opened state for Superb

- .github/workflows/test.yaml
- scripts/__init__.py
- scripts/gen_ref_nav.py
- added __init__.py file to scripts
- fixed missing empty line at the end of scripts/gen_ref_nav.py
- fixed import in scripts/gen_ref_nav.py
- added docs to extras so lint can succeed
> Fix ruff and pyright reported errors

- myskoda/models/charging.py
Kinda weird this is missing only for some cars/users (when not charging)...
Fixes skodaconnect/homeassistant-myskoda#28
> Fix missing field in ChargingStatus

- myskoda/cli.py
- myskoda/models/air_conditioning.py
- tests/fixtures/enyaq/air-conditioning-heating.json
- tests/test_rest_api.py
Tests added.
Fixes https://github.com/skodaconnect/homeassistant-myskoda/issues/38
> Fix state for air conditioning

- myskoda/models/info.py
> Make Specification.trim_level optional

- myskoda/models/status.py
- tests/fixtures/superb/vehicle-status-left-back-door-trunk-bonnet-opened.json
- tests/test_rest_api.py
- tests/test_status.py
Calculated from renders that response messsage contains. Probably not very reliable method. Error cases assumed, return closed state if parsing fails for any reason.
Added tests for different states.
> Add calculated state of the doors and windows

- myskoda/models/air_conditioning.py
Fixes https://github.com/skodaconnect/homeassistant-myskoda/issues/52
> Add 'VENTILATION' state

- myskoda/models/common.py
Make "city" optional to address https://github.com/skodaconnect/homeassistant-myskoda/issues/47
> Make "city" field in Address optional

- myskoda/cli.py
- myskoda/myskoda.py
- myskoda/rest_api.py
- pyproject.toml
This is an alternative suggestion to #49
> Allow MQTT to be disabled

- myskoda/models/air_conditioning.py
- myskoda/models/charging.py
- tests/fixtures/other/air-conditioning-idle.json
- tests/fixtures/superb/air-conditioning-aux-heater.json
- tests/fixtures/superb/air-conditioning-idle.json
- tests/fixtures/superb/charging-iV.json
- tests/test_rest_api.py
Tests added.
Many fields have to be made optional because they do not exist in Superb responses.
I would appreciate if someone provides similar data from other cars so we can embed fixtures to the tests.
> Fix air-conditioning and charging response processing

- myskoda/models/driving_range.py
- tests/fixtures/enyaq/driving-range-iv80-car-type-electric.json
- tests/fixtures/superb/driving-range-car-type-hybrid.json
- tests/test_driving_range.py
> Fix driving range parsing for hybrid cars

- myskoda/models/charging.py
> Make max_charge_current_ac optional

- myskoda/auth/authorization.py
- myskoda/cli.py
Adds detection for windows platform for cli and main authorization flow
Fixes #77
> Windows compatibility

- myskoda/models/info.py
Adds a new bodytype
Fixes skodaconnect/homeassistant-myskoda#88
> Add bodytype Hatchback

- myskoda/models/maintenance.py
Fixes skodaconnect/homeassistant-myskoda#92
> Add Phone as a valid communications channel

- myskoda/__init__.py
- myskoda/auth/authorization.py
This improves detection of authentication errors, so this can be picked up by the HA integration more gracefully
> Improve detection of authentication errors

- myskoda/models/air_conditioning.py
Fixes skodaconnect/homeassistant-myskoda#99
> Add INVALID state to AirConditioning state

- myskoda/models/common.py
Needed for skodaconnect/homeassistant-myskoda#98
> Add INVALID value for ChargerLockedState

- fixtures/octaviacombi.yaml
Contributing fixture of my Octavia Combi
> Octavia Combi Fixture

- myskoda/models/garage.py
- myskoda/models/info.py
> Handle the case of an empty garage

- myskoda/models/common.py
- pyproject.toml
Fixes skodaconnect/homeassistant-myskoda#113
> Make zipcode optional

- fixtures/nx53l5_octavia_2024_combi_deepsleep_0.8.3.yaml
Update Octavia 2024 fixture to myskoda 0.8.3.
Fixed error: _Field "status" of type Optional[ChargingStatus] is missing in Charging instance_
> Update Octavia 2024 fixture to myskoda 0.8.3

- myskoda/models/common.py
> Add NotAllowed as EnabledState

- myskoda/auth/authorization.py
> Fix KeyError when upstream API fails

- myskoda/models/garage.py
Fixes homeassistant-myskoda#139
> Add Unknown ErrorType

- myskoda/models/info.py
This fixes skodaconnect/homeassistant-myskoda#138
> Add guest user state

- myskoda/models/user.py
This fixes the profile picture not always used by users
Closes skodaconnect/homeassistant-myskoda#135
> Fix profile picture not always used

- myskoda/models/common.py
Fixes skodaconnect/homeassistant-myskoda#145
> Make street in Address optional

- fixtures/nu74nv_karoq_expired_subscription.yaml
> Add fixture for a Karoq with expired subscriptions

- myskoda/models/trip_statistics.py
Fixes skodaconnect/homeassistant-myskoda#160
> Make overall_average_fuel_consumption optional

- fixtures/nu74nv_karoq_expired_subscription.yaml
- fixtures/nx53l5_octavia_2024_combi_deepsleep_0.8.3.yaml
- fixtures/prior99_enyaq_iv60_idle_full_battery.yaml
- fixtures/prior99_octavia_2018.yaml
- fixtures/superb_iv_2020_3v35xc_liftback_l_and_k.yaml
- fixtures/webspider_enyaq_iv80_parked_deep_sleep_positioning_off.yaml
- myskoda/models/air_conditioning.py
- Add airconditioning without external power field (SuperB iV)
- Fix heatersource to allow Electric (SuperB iV)
Fixes skodaconnect/homeassistant-myskoda#171
> Fixes for Superb iV

- myskoda/models/position.py
Fixes skodaconnect/homeassistant-myskoda#176
> Add VEHICLE_POSITION_UNAVAILABLE error messsage

- myskoda/models/trip_statistics.py
Fixes skodaconnect/homeassistant-myskoda#169
> Make overall_averiage_mileage_in_km optional

- myskoda/models/garage.py
Fixes skodaconnect/homeassistant-myskoda#190
> Add error of a missing render

- myskoda/models/trip_statistics.py
Fixes skodaconnect/homeassistant-myskoda#196
> Make overall_average_speed_in_kmph optional

- myskoda/models/info.py
#169 had a fixtures file from a Skoda Octavia with an ICU.
This PR processes the new features from them
Most importantly: We can determine if a car has an external temperature sensor :tada:
> Add features and errors from Octavia (ICU)

- fixtures/karoq-se-l_2023.yaml
> Skoda Karoq SE L 2023 fixture

- fixtures/karoq-se-l_2023.yaml
- pyproject.toml
- Add ad_blue_range to fixture
> Prepare release 0.9.0

- myskoda/models/trip_statistics.py
Fixes skodaconnect/homeassistant-myskoda#219
> Make overall_average_travel_time optional

- fixtures/kamiq.yaml
> Add fixture for kamiq

- myskoda/models/driving_range.py
Fixes skodaconnect/homeassistant-myskoda#224
> Make EngineRange.remaining_range_in_km optional

- fixtures/superb_iv_combi_2022_3V53XC_standing_still.yaml
- myskoda/models/trip_statistics.py
These 2 fields need to be optional too. I guess this is because my car has been standing still at the dealers. I added my fixtures too to compare.
> More trip statistics optional

- myskoda/models/charging.py
> fix: make remainingCruisingRangeInMeters field optional

- pyproject.toml
> Prepare release 0.11.0

- myskoda/models/user.py
> Make country inside User optional

- myskoda/auth/authorization.py
Implements detection for a redirect to a Terms and Conditions page and adds a new exception for better handling in the integration
> Terms and Conditions during login

- fixtures/djapollo_enyaq_85_2025.yaml
> Add fixture for an Enyaq 85

- pyproject.toml
> Prepare update to 0.12.2

- fixtures/kamiq.yaml
- fixtures/my_favorite_car.yaml
- fixtures/superb_iv_2020_3v35xc_liftback_l_and_k.yaml
- myskoda/anonymize.py
Fixes #227
Tested with the previous raw response from one of the updated fixtures
```python
>>> anonymize_maintenance(test)
{'maintenanceReport': {'capturedAt': '2024-11-09T10:23:54Z', 'inspectionDueInDays': 489, 'inspectionDueInKm': 15500, 'mileageInKm': 77043, 'oilServiceDueInDays': 489, 'oilServiceDueInKm': 15500}, 'preferredServicePartner': {'name': 'Example Service Partner', 'brand': 'C', 'partnerNumber': '1111', 'id': 'DEU11111', 'contact': {'phone': '+49 1234 567890', 'url': 'https://example.com', 'email': 'user@example.com'}, 'address': {'city': 'Example City', 'street': 'Example Avenue', 'houseNumber': '15', 'zipCode': '54321', 'countryCode': 'DEU'}, 'location': {'latitude': 53.470636, 'longitude': 9.689872}, 'openingHours': [{'periodStart': 'MONDAY', 'periodEnd': 'FRIDAY', …
```
> Anonymize booking/maintenance history in fixtures

- README.md
Fixes skodaconnect/homeassistant-myskoda#318
> Add disclaimer in README

- myskoda/cli/__init__.py
- myskoda/cli/operations.py
- myskoda/models/air_conditioning.py
- myskoda/myskoda.py
- myskoda/rest_api.py
- tests/test_operations.py
- set_ac_at_unlock (enable/disable AC at unlock)	
- set_seats_heating (enable/disable seats[frontLeft,frontRight] heating with AC)
- set_windows_heating (enable/disable windows heating with AC)
> Implement 3 missing AC setting methods

- fixtures/Octavia2023_w_aux_heating.yaml
- fixtures/djapollo_enyaq_85_2025.yaml
- fixtures/kamiq.yaml
- fixtures/karoq-se-l_2023.yaml
- fixtures/my_favorite_car.yaml
- fixtures/nu74nv_karoq_expired_subscription.yaml
- fixtures/nx53l5_octavia_2024_combi_deepsleep_0.8.3.yaml
- fixtures/octavia_2022.yaml
- fixtures/prior99_enyaq_iv60_idle_full_battery.yaml
- fixtures/prior99_octavia_2018.yaml
- fixtures/skoda_octavia_combi_2023.yaml
- fixtures/superb_iv_2020_3v35xc_liftback_l_and_k.yaml
- fixtures/superb_iv_2021_3v54xc.yaml
- fixtures/superb_iv_combi_2022_3V53XC_standing_still.yaml
- fixtures/webspider_enyaq_iv80_parked_deep_sleep_positioning_off.yaml
- myskoda/models/fixtures.py
- myskoda/myskoda.py
> Add library_version to fixture

- pyproject.toml
> Prepare release 0.13.0

- myskoda/models/charging.py
Fixes skodaconnect/homeassistant-myskoda#364
> Make state_of_charge optional

- fixtures/octavia_iv_2022_nx34vc_liftback_style.yaml
> fixtures from Octavia iV Style 2022

- fixtures/Fixtures_for_Kodiaq_Style_2023.yaml
- fixtures/Octavia2023_w_aux_heating.yaml
- fixtures/citigoe_iv_2021_ne142e2_best_of.yaml
- fixtures/kamiq.yaml
- fixtures/karoq-se-l_2023.yaml
- fixtures/nx53l5_octavia_2024_combi_deepsleep_0.8.3.yaml
- fixtures/octavia_2022.yaml
- fixtures/octavia_iv_2021_nx56xc_combi_rs.yaml
- fixtures/octavia_iv_2022_nx34vc_liftback_style.yaml
- fixtures/prior99_octavia_2018.yaml
- fixtures/skoda_octavia_combi_2023.yaml
- fixtures/superb_2024_3v35wz_liftback_l_and_k.yaml
- fixtures/superb_iv_2020_3v35xc_liftback_l_and_k.yaml
- fixtures/superb_iv_2021_3v54xc.yaml
- fixtures/superb_iv_combi_2022_3V53XC_standing_still.yaml
- myskoda/models/trip_statistics.py
- averageGasConsumption
- overallAverageGasConsumption
- vehicleType = GAS
> update trip_statistics with Gas

- myskoda/models/info.py
https://github.com/skodaconnect/homeassistant-myskoda/issues/449
> add RESET_SPIN into VehicleState

- myskoda/models/status.py
- tests/test_status.py
working on implementation of binary sensor for each door to detect window/door opened/closed and noticed we are missing state where both door and window is opened (state=4)
> add missing state for both Window and Door open

- myskoda/auth/authorization.py
- myskoda/cli/__init__.py
- myskoda/cli/operations.py
- myskoda/myskoda.py
- myskoda/rest_api.py
- tests/test_operations.py
Enable or disable auto unlock plug when charged
(needs to be tested as I don't have this feature and just took it from decompiled apk)
> add CableLock feature (set_auto_unlock_plug)

- fixtures/citigoe_iv_2020_ne14e2_style.yaml
> add fixture for CitigoE iV 2020 style

- fixtures/enyaq_2023_5AZJJ2_80.yaml
- myskoda/mqtt.py
- tests/test_generated.py
> fix tests for URLs with dynamic query string

- fixtures/djapollo_enyaq_85_5AZJK2.yaml
Updated the fixture to the latest lib version as it was reset to the oldest version (i.e. no external temp) after fixture cleanup
> Updated Enyaq 2025 to fixture from 0.16.2 lib

- fixtures/webspider_enyaq_2021_5AZJJ2.yaml
> Update fixtures for my Enyaq

- docs/api_endpoints.md
- fixtures/djapollo_enyaq_85_5AZJK2.yaml
- fixtures/enyaq_2023_5AZJJ2_80.yaml
- fixtures/kodiaq_2024_ps7d6z_exclusive.yaml
- fixtures/octavia_2022.yaml
- fixtures/octavia_2023_NX34JD_style.yaml
- fixtures/octavia_2023_NX53L5_combi.yaml
- fixtures/octavia_2024_NX53L5_combi.yaml
- fixtures/prior99_enyaq_2024_5AZFF2_idle_full_battery.yaml
- fixtures/sonar98_enyaq_2022_5AZJJ2.yaml
- fixtures/superb_2024_3v35wz_liftback_l_and_k.yaml
- fixtures/webspider_enyaq_2021_5AZJJ2.yaml
- myskoda/cli/__init__.py
- myskoda/cli/operations.py
- myskoda/models/air_conditioning.py
- myskoda/models/auxiliary_heating.py
- myskoda/myskoda.py
- myskoda/rest_api.py
- tests/test_operations.py
- tests/test_rest_api.py
already tested by @WebSpider and working as expected
> add set air-conditioning timers feature

- fixtures/kodiaq_iv_2024_ps7dyc_selection.yaml
> add Fixture for Kodiaq iV

- docs/api_endpoints.md
- myskoda/cli/__init__.py
- myskoda/cli/operations.py
- myskoda/models/auxiliary_heating.py
- myskoda/myskoda.py
- myskoda/rest_api.py
- tests/test_operations.py
lets put the code into our lib so it will be easier to test it
> Auxiliary heating timers

- myskoda/rest_api.py
Sets the default value of the User object timestamp to the current second
> Set default value of User object timestamp

- myskoda/rest_api.py
- tests/test_generated.py
> Set default value of Info object timestamp

- myskoda/const.py
- myskoda/models/vehicle_ignition_status.py
- myskoda/mqtt.py
- myskoda/myskoda.py
Fixes skodaconnect/homeassistant-myskoda#512
> Add timeout to MQTT events so we do not wait forever for them to resolve

- fixtures/karoq_2020_nu74nd_businessline.yaml
From https://github.com/skodaconnect/homeassistant-myskoda/issues/468 to help investigate too many requests on warning-lights endpoint.
> Add Karoq fixture from 468

- docs/rest.md
Used to track order of a new vehicle.
Probably needs a few more examples later on, when orderStatus changes.
Assuming that would include some more information, if that has any interest as well 😄
> Add example info about "Get ordered vehicle details" endpoint

- docs/api_endpoints.md
- myskoda/anonymize.py
- myskoda/auth/authorization.py
- myskoda/cli/__init__.py
- myskoda/cli/gen_fixtures.py
- myskoda/cli/requests.py
- myskoda/models/chargingprofiles.py
- myskoda/models/fixtures.py
- myskoda/mqtt.py
- myskoda/myskoda.py
- myskoda/rest_api.py
- tests/fixtures/enyaq/charging-profiles.json
- tests/test_rest_api.py
Implements parsing the response of the /v1/charging/vin/profiles URL, providing information on saved charge locations and their profiles.
> Initial implementation of charging profiles

- myskoda/auth/authorization.py
- myskoda/cli/gen_fixtures.py
- myskoda/mqtt.py
This fixes 2 linter issues:
- Remove some unused imports
- ~~Rewrite of the event handler to be more scalable~~
> Fix linter warnings

- docs/api_endpoints.md
Updating api_endpoints.md with the latest endpoints from MySkoda app version 8.1
> Add new API endpoints from MySkoda v8.1 app

- docs/api_endpoints.md
Quick scan for replies from new URLs
> Add replies from new URLs

- .readthedocs.yaml
The readthedocs job works fine with uv: https://app.readthedocs.org/projects/myskoda/builds/27630455/
> Remove remaining obsolete poetry reference

- myskoda/auth/authorization.py
- myskoda/mqtt.py
- myskoda/myskoda.py
- myskoda/rest_api.py
- myskoda/vehicle.py
- pyproject.toml
Potential alternative solution for https://github.com/skodaconnect/homeassistant-myskoda/issues/731
TODO:
- MySkoda now handles the callbacks itself so it can process events before emitting them to registered callbacks.
- https://github.com/skodaconnect/homeassistant-myskoda/pull/737
Test (note the event processing and API GETs coming from myskoda directly and not the coordinator)
```
2025-04-01 20:00:39.970 DEBUG (MainThread) [myskoda.mqtt] Message (service-event) received for TMBJXXXXXXXXXXXX on topic charging: b'{"version":1,"traceId":"1f7bcdc4-d95b-4812-b517-b2a9662d81e5","timestamp":"2025-04-01T18:00:37Z","producer":"SKODA_MHUB","name":"change-soc","data":{"mode":"manual","state":"charging","soc":"77","chargedRange":"315","timeToFinish":"105","userId":"12345","vin":"TMBJXXXXXXXXXXXX"} …
```
> Update vehicle cache with MQTT event data

- myskoda/models/user.py
Fixes https://github.com/skodaconnect/homeassistant-myskoda/issues/747
> Fix: user.nickname is optional

- myskoda/models/chargingprofiles.py
> Fix: Make next_charging_time optional

- fixtures/octavia_2022_NX34ED_cng.yaml
From https://github.com/skodaconnect/homeassistant-myskoda/issues/760
> test: add fixture for hybrid cng octavia

- docs/api_endpoints.md
- myskoda/cli/__init__.py
- myskoda/cli/operations.py
- myskoda/myskoda.py
- myskoda/rest_api.py
Implementing ventilation according to https://github.com/skodaconnect/myskoda/blob/main/docs/api_endpoints.md
> Add start/stop ventilation (air-conditioning)

- docs/api_endpoints.md
- myskoda/anonymize.py
- myskoda/cli/__init__.py
- myskoda/cli/requests.py
- myskoda/models/vehicle_connection_status.py
- myskoda/myskoda.py
- myskoda/rest_api.py
Basic implementation for the `/v2/connection-status/{vin}/readiness` endpoint storing the response as-is
Prereq for skodaconnect/homeassistant-myskoda#751
> feat: implement vehicle connection state endpoint

- CONTRIBUTING.md
This adds a LLM-generated contribution guideline with some manual tweaks
Fixes #406
> docs: add contribution styleguide

- myskoda/models/position.py
Fixes https://github.com/skodaconnect/homeassistant-myskoda/issues/787
> fix: position.address is now optional

- myskoda/models/charging.py
Fixes skodaconnect/homeassistant-myskoda#819
> fix: add new ChargMode.OTHER

- myskoda/models/maintenance.py
Fixes skodaconnect/homeassistant-myskoda/issues/840
> fix: Booking.update_date is optional

- myskoda/anonymize.py
- myskoda/cli/__init__.py
- myskoda/cli/requests.py
- myskoda/models/position.py
- myskoda/myskoda.py
- myskoda/rest_api.py
- myskoda/vehicle.py
This adds the `parking_position` in addition to the already existing `positions`.
At some point the integration is probably going to switch once we feel this new API brings enough advantages.
> feat: implement parking position 

- docs/api_endpoints.md
Updating api_endpoints.md with the latest endpoints from MySkoda app version 8.4.0
> Add new API endpoints from MySkoda v8.4.0 app

- myskoda/models/user.py
- myskoda/mqtt.py
- myskoda/myskoda.py
- myskoda/rest_api.py
- myskoda/vehicle.py
Cleaning up the test reports a little by marking code that doesn't need to be tested as such.
> Ignore code that doesnt need testing

- fixtures/webspider_enyaq_2021_5AZJJ2_80.yaml
- myskoda/models/vehicle_connection_status.py
Reported by AJTaylor79 in Discord for an Enyaq MY25
> Add ignition_on field to vehicle_connection_status

- fixtures/elroq_2025_PYLQK2_Sportline.yaml
- fixtures/enyaq_2025_5azjk2_85.yaml
- fixtures/webspider_enyaq_2021_5AZJJ2_80.yaml
- myskoda/anonymize.py
This one fixes https://github.com/skodaconnect/myskoda/issues/477
> fix: change anonymize_chargingprofiles
