myskoda/models/info.py, myskoda/models/mqtt.py, myskoda/rest_api.py
Logging API responses will help debugging issues reported by users, like https://github.com/skodaconnect/homeassistant-myskoda/issues/18
I started working on replacing pydantic with mashumaro but I'm not convinced yet. Pydantic does a lot of nice things and does them elegantly, like this additional validator which will drop unknown capabilities. It also enforces types and even coerces 'wrong' types into the desired type. So these validators to convert str to int aren't actually required. Use pydantic (`.parse_raw()`) to de-serialize the json responses.
=> Drop and log unknown capabilities, log responses, deserialize with Pydantic

myskoda/models/info.py, tests/fixtures/enyaq/garage_vehicles_iv80_coupe.json, tests/test_rest_api.py
Fixes skodaconnect/homeassistant-myskoda#18
=> Add SUV Coupe BodyType

myskoda/__init__.py, myskoda/cli.py, myskoda/myskoda.py
See https://docs.aiohttp.org/en/stable/client_advanced.html#client-tracing
Example:
```
❯ poetry run myskoda --user foo@gmail.com --password 'bar' --verbose auth
...
2024-09-21 19:19:55 WALLY myskoda.myskoda[14829] DEBUG Trace: GET https://mysmob.api.connect.skoda-auto.cz/api/v1/users - response: 200 (643 bytes) {"id":"123","email":"fabrice.devaux@gmail.com","firstName":"Foo","lastName":"Bar","nickname":"Foo","country":"BE","preferredLanguage":"en","phone":"+12345","billingAddress":{"country":"BE","city":"Stormwind","street":"Foo","houseNumber":"1","zipCode":"90218"},"capabilities":[{"id":"SPIN_MANAGEMENT"},{"id":"THIRD_PARTY_OFFERS"},{"id":"MARKETING_CONSENT"}],"preferredContactChannel":"MARKETING_BLOCKADES:EMAIL","profilePictureUrl":"https://mysmob.api.connect.skoda-auto.cz/api/v1/users/ …
```
=> Add API response tracing

.github/workflows/publish.yaml
Auto build and publish the package to PyPI when a release is created in Github. We had this in the old project but based on flit instead of poetry. 
Requires a one-time setup to authorize the project in PyPI: https://github.com/marketplace/actions/pypi-publish#trusted-publishing
@Prior99 can you please add @WebSpider and myself as maintainers in PyPI?
=> Add workflow to publish to PyPI

myskoda/cli.py, myskoda/models/maintenance.py
Make phone and preferred_channel optional in predictive maintenance setting:
- Phone is not always filled in. Fixes my issue (https://github.com/skodaconnect/homeassistant-myskoda/issues/34)
- Preferred Channel is also not always present. Fixes issue (https://github.com/skodaconnect/homeassistant-myskoda/issues/33)
Also made the "phone" print nicer when using the CLI (prints a "-" instead of None)
=> Adjust PredictiveMaintenanceSettings

myskoda/models/air_conditioning.py
I guess when the car doesn't have heated seats.
Fixes skodaconnect/homeassistant-myskoda#43
=> Fix seat_heating_activated being optional

myskoda/models/charging.py
When there is a charging error, the charging state is not always included in the API reply. Make the field optional
Also, include the charging error as we find them
Fixes https://github.com/skodaconnect/homeassistant-myskoda/issues/36
=> (bug) Fix charging model to include errors

myskoda/models/info.py, myskoda/mqtt.py, myskoda/myskoda.py, pyproject.toml
Following some remarks this week about f-style and logging:
Remove f-style strings from logging statements and disable G004 exception
=> Remove ruff G004 exception

myskoda/models/info.py
If you haven't chosen a Service Partner yet in the app this field is not sent from the API.
If something isn't correct let me know!
@dvx76 
Edit: fixes #63 and skodaconnect/homeassistant-myskoda#50
=> Make Service Partner optional in Info

myskoda/models/air_conditioning.py
This PR adds the missing 'COOLING' state to the AirConditioningState enum in response to issue #79. The issue reported a ValueError due to the missing 'COOLING' state, and I've updated the enum to include this state.
This is my first open source contribution, and I'm excited to be part of the community. Please feel free to provide any feedback or guidance if there's anything I can improve. Thanks.
=> #79 Add 'COOLING' state to AirConditioningState

myskoda/mqtt.py
The same event gets processed over and over again if there is an exception in _on_message.
Not super happy with this fix but haven't found a better way. Discord discussion: https://discord.com/channels/877164727636230184/1087487796731707402/1292485603375448154
Fixes skodaconnect/homeassistant-myskoda#63
=> Fix crashloop when failing to parse MQTT events

myskoda/models/charging.py, myskoda/models/common.py
Some endpoints and/or MQTT events return their values as uppercase for some users and lowercase for other users.
Fixes #55
=> Support case-insensitive StrEnums

myskoda/cli.py, myskoda/rest_api.py
I tried to add a minimal solution to better handle the trip-statistics error:
- Added an exception in the rest_api module. The _make_get_request still throws an exception, so behaviour in the overall library should remain the same
- The CLI catches the new exception and prints it
This should fix #58 , at least by printing the error result instead of throwing an exception.
It also takes into account @dvx76 's remark  that 
> The integration will use get_vehicle which will only try to get statistics if the TRIP_STATISTICS capability is present.
The CLI also still exposes all methods but does not error in case there are no trip statistics.
The fix is minimal in the sense that I think it would be overkill for the trip-statistics method to first check the capabilities and then - depending on …
=> Error handling for trip-statistics in CLI

myskoda/models/charging.py
Allows for the case where the car is connected, but charger is not supplying info/power
=> Set default value of ChargingState to None

myskoda/rest_api.py
Make the REST API wait for the result before returning the client response.
The _make_request now waits until the text() is there before returning the ClientResponse object. This prevents the connection being closed too early.
Making the _make_request method await on the text() also removes the need for post and put methods to do this.
This solves #90
=> Make the REST API wait for the result

myskoda/models/service_event.py
Apparently, timeToFinish can be "null" according to issue skodaconnect/homeassistant-myskoda/issues/78
This adds a deserializer to handle the case
=> Add deserialization for time_to_finish

myskoda/cli/__init__.py
Move event loop policy check to global scope to initalize at very startup.
It seems that the event loop policy was set too late, or at least for me. Moving it to the global scope did the trick.
Fixes #116
=> WindowsSelectorEventLoopPolicy to global scope

myskoda/anonymize.py, myskoda/myskoda.py, myskoda/rest_api.py
Use regex to find VINs, based on VINs being 17 characters and the Skoda WMI being `TMB`.
Ref: https://www.skoda-storyboard.com/en/skoda-world/what-can-vin-codes-tell-you/
Fixes #100
In retrospect the original VIN is available where the additional call to `anonymize_url` is used so I could have kept the basic string `.replace`. But using regex allows this to be used from anywhere if we need to.
Also maybe I should rename `anonymize_url` to `anonymize_vin`?
=> Anonymize VIN in errors saved in fixtures

myskoda/mqtt.py
Might help debugging some of the MQTT issues we're seeing.
Note: ha-core mqtt integration does the same thing.
Example (with `--verbose` / log-level DEBUG):
```
2024-10-28 09:54:33 WALLY myskoda.mqtt[4123] DEBUG Subscribing to topic: uuid/TMBXXXX/account-event/account-event/privacy
2024-10-28 09:54:33 WALLY paho.mqtt.client[4123] DEBUG Sending SUBSCRIBE (d0, m26) [(b'uuid/TMBXXXX/account-event/account-event/privacy', 0)]
2024-10-28 09:54:33 WALLY paho.mqtt.client[4123] DEBUG Received SUBACK
2024-10-28 09:54:47 WALLY paho.mqtt.client[4123] DEBUG Sending PINGREQ
2024-10-28 09:54:47 WALLY paho.mqtt.client[4123] DEBUG Received PINGRESP
```
=> Enable mqtt logging

myskoda/mqtt.py
Not fully clear about this yet but should at least help avoid skodaconnect/homeassistant-myskoda#140 and #123
When _something_ causes the MQTT connection to drop both the `on_disconnect` and the `on_socket_close` fire and both trigger a reconnect. This leads to a `ConcurrentSubscribeError` and all kinds of weird networking and stability issues throughout HA as a result.
=> Temporary workaround for MQTT ConcurrentSubscribeError and stability

fixtures/nx53l5_octavia_2024_combi_deepsleep_0.8.3.yaml, fixtures/prior99_enyaq_iv60_idle_full_battery.yaml, fixtures/prior99_octavia_2018.yaml, fixtures/skoda_octavia_combi_2023.yaml, fixtures/superb_iv_2020_3v35xc_liftback_l_and_k.yaml, fixtures/webspider_enyaq_iv80_parked_deep_sleep_positioning_off.yaml, myskoda/models/driving_range.py
Fixes skodaconnect/homeassistant-myskoda#187
=> Fix driving range model for Octavia NX

myskoda/models/service_event.py
Superb iV (MY 2020) does not send any additional data in the charging-status-changed event so the exception happens and warning is printed in the logs.
This can be observed from logs:
```
2024-11-09 15:30:34.512 DEBUG (MainThread) [myskoda.mqtt] Received PUBLISH (d0, q0, r0, m0), '97bee240-dd09-4d56-8d8b-fbdfxxxxxxxx/TMBAXXXXXXXXXXXXX/service-event/charging', ...  (237 bytes)
2024-11-09 15:30:34.513 DEBUG (MainThread) [myskoda.mqtt] Message (service-event) received for TMBAXXXXXXXXXXXXX on topic charging: b'{"version":1,"traceId":"81b50439-af83-44e1-9515-5b3925d4c34a","timestamp":"2024-11-09T13:30:34Z","producer":"SKODA_MHUB","name":"charging-status-changed","data":{"userId":"97bee240-dd09-4d56-8d8b-fbdfxxxxxxxx","vin":"TMBAXXXXXXXXXXXXX"}}'
2024-11-09 15:30:34.513 WARNING (MainThread) …
```
=> Make fields of ServiceEventChargingData optional

myskoda/cli/__init__.py, myskoda/cli/operations.py, myskoda/cli/requests.py, myskoda/const.py, myskoda/models/spin.py, myskoda/myskoda.py, myskoda/rest_api.py, tests/fixtures/superb/verify-spin-correct.json, tests/fixtures/superb/verify-spin-incorrect.json, tests/test_operations.py, tests/test_rest_api.py
- Added auxiliary heater support (start/stop). For some reason progress is not published via MQTT so request is just send and not awaited for COMPLETED_SUCCESS status
- Added verify_spin method which returns `CORRECT_SPIN` or `INCORRECT_SPIN` and S-Pin status
=> Add start/stop auxiliary-heating and verify_spin support

myskoda/models/driving_range.py
Log entries:
```
2024-11-13 00:49:12.301 ERROR (MainThread) [myskoda.rest_api] Failed to deserialize data: {"carType":"hybrid","totalRangeInKm":770,"primaryEngineRange":{"engineType":"gasoline","currentSoCInPercent":93,"currentFuelLevelInPercent":93,"remainingRangeInKm":770},"secondaryEngineRange":{"engineType":"electric","remainingRangeInKm":0},"carCapturedTimestamp":"2024-11-12T17:54:48Z"}
Traceback (most recent call last):
File "<string>", line 31, in __mashumaro_from_json__
File "<string>", line 7, in __mashumaro_from_dict_json__
mashumaro.exceptions.MissingField: Field "current_soc_in_percent" of type int is missing in EngineRange instance
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File …
```
=> Some fields are not present in Superb iV 2020 response to driving_range

myskoda/models/service_event.py, tests/test_mqtt.py
and new state `chargePurposeReachedAndConservation`.
Fixes skodaconnect/homeassistant-myskoda#253
=> Add charging-complete ServiceEvent

myskoda/models/maintenance.py
inspection_due_in_days is optional.
Fixes #237
=> Fix optional field in MaintenanceReport

myskoda/event.py, myskoda/models/service_event.py, myskoda/mqtt.py, tests/fixtures/events/service_event_charging_change_soc.json, tests/fixtures/events/service_event_charging_charging_status_changed.json, tests/fixtures/events/service_event_departure.json, tests/test_mqtt.py, tests/test_service_event.py
The structures are discriminated based on the "name" field in the received event.
I have tried to test this change on my Superb iV but apparently the car does not really send much events. I would appreciate if this  change is tested by someone.
Fixes #184
=> Create ability to define structures per service event

myskoda/__init__.py, myskoda/__version__.py, myskoda/models/maintenance.py, myskoda/myskoda.py, pyproject.toml
This PR does two things:
1) Introduce dynamic versioning from git tags
2) Fix skodaconnect/homeassistant-myskoda#353 by removing the blocking module
This means the version is dynamically placed inside `myskoda/__version__.py` by poetry when building the module. We alsno no longer need to bump the version in `pyproject.toml`
The version is now obtained from the latest tag or commit
=> Switch to dynamic module versioning

fixtures/Octavia2023_w_aux_heating.yaml, fixtures/citigoe_iv_2021_ne142e2_best_of.yaml, fixtures/djapollo_enyaq_85_2025.yaml, fixtures/kamiq.yaml, fixtures/karoq-se-l_2023.yaml, fixtures/kodiaq_2024_ps7d6z_exclusive.yaml, fixtures/nu74nv_karoq_expired_subscription.yaml, fixtures/nx53l5_octavia_2024_combi_deepsleep_0.8.3.yaml, fixtures/octavia_2022.yaml, fixtures/octavia_iv_2021_nx56xc_combi_rs.yaml, fixtures/prior99_enyaq_iv60_idle_full_battery.yaml, fixtures/prior99_octavia_2018.yaml, fixtures/skoda_octavia_combi_2023.yaml, fixtures/sonar98_Enyaq_iV80_2022_software_3.0.yaml, fixtures/superb_2024_3v35wz_liftback_l_and_k.yaml, fixtures/superb_iv_2020_3v35xc_liftback_l_and_k.yaml, fixtures/superb_iv_2021_3v54xc.yaml, fixtures/superb_iv_combi_2022_3V53XC_standing_still.yaml, fixtures/webspider_enyaq_iv80_parked_deep_sleep_positioning_off.yaml, myskoda/models/air_conditioning.py, myskoda/models/auxiliary_heating.py
+ created OutsideTemperature class derived from TargetTemperature
=> added outsideTemperature into AirConditioning class

myskoda/mqtt.py, myskoda/myskoda.py
This makes MQTT reconnect backoff exponential so we do not hammer MQTT server if it is in an error state.
Observed in todays MQTT outage that we reconnect every 5s, which is very rapid when running this distributed and at scale. 
We do not need to DOS the MQTT server while trying to get our updates, so implementing an industry-standard solution (exponential backoff with jitter) to this, seems like a reasonable addition.
=> Introduce exponential backoff for MQTT reconnect

fixtures/Fixtures_for_Kodiaq_Style_2023.yaml
=> Add fixture Kodiaq from chodorenko

myskoda/auth/authorization.py
during login the process can halt because the user is redirected to a marketing constent page. Without catching this condition a KeyError Location is raised because it's the final page but doesn't start with `myskoda://`.
Ref #277
=> Add exception for redirect to marketing consent

docs/api_endpoints.md, myskoda/cli/__init__.py, myskoda/cli/operations.py, myskoda/const.py, myskoda/myskoda.py, myskoda/rest_api.py, tests/test_operations.py
Part of departure timers - used when there is at least 1 active timer. Car will charge to the specified SoC after connecting charging cable and stop charging when specified SoC is reached. Rest is charged using departure timer rules.
=> Add set-minimum-charge-limit feature

myskoda/cli/requests.py
Fixes:
```sh
$ myskoda --user <MYSKODA_EMAIL> --password <MYSKODA_PASSWORD> auth
<coroutine object MySkoda.get_auth_token at 0x106921cc0>
./myskoda/myskoda/cli/requests.py:151: RuntimeWarning: coroutine 'MySkoda.get_auth_token' was never awaited
print(myskoda.get_auth_token())
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```
=> fix(cli): missing await in auth command

.github/workflows/test.yaml
The apt repository we're using for installing `Just` has been showing issues lately.
This is now swapped with the snap alternative.
=> Fix CI tests

myskoda/models/air_conditioning.py, tests/fixtures/enyaq/air-conditioning-no-steering.json, tests/test_rest_api.py
related to https://github.com/skodaconnect/homeassistant-myskoda/issues/548
=> make steeringWheelPosition and windowHeatingState optional

myskoda/models/user.py
This adds logging of unknown capabilities instead of crashing hard when an unknown capability is encountered
Prevents issues such as skodaconnect/homeassistant-myskoda#598
=> Improve deserialisation stability for User

myskoda/models/charging.py, myskoda/models/service_event.py, tests/fixtures/events/service_event_charging_charging_error.json, tests/fixtures/events/service_event_departure_error_plug.json, tests/test_mqtt.py, tests/test_service_event.py
I discovered another error that was published via MQTT:
```
2025-01-30 17:30:34 python myskoda.mqtt[2702] DEBUG Message (service-event) received for TMBAXXXXXXXXXXXXX on topic departure: b'{"version":1,"traceId":"7b586354-fc7b-474a-bd6a-d69bbec13fa1","timestamp":"2025-01-30T16:30:30Z","producer":"SKODA_MHUB","name":"departure-error-plug","data":{"errorCode":"CLIMA","userId":"00000000-0000-0000-0000-000000000000","vin":"TMBAXXXXXXXXXXXXX"}}'
```
To add handling for this, I'd suggest to move the "charging-error" out of "models/charging.py" back into "models/service-event.py" and revert the adding of "error-code" to "ServiceEventChargingData" and to use a separate "ServiceEventErrorData" instead.
I'm not totally sure, why or when this error was fired - but maybe this opens the door to handle …
=> Add support for mqtt departure-error-plug message

myskoda/myskoda.py
This will be used by the client to selectively exclude specific endpoints/capabilities, e.g. based on a timer.
This will replace the selective inclusion of the VEHICLE_HEALTH_INSPECTION capability in get_partial_vehicle() so this is removed here.
Required to resolve https://github.com/skodaconnect/homeassistant-myskoda/issues/468
=> Support excluded_capabilities in get_vehicle

myskoda/models/air_conditioning.py, myskoda/models/auxiliary_heating.py, myskoda/models/charging.py, myskoda/models/common.py, myskoda/models/departure.py, myskoda/models/driving_range.py, myskoda/models/garage.py, myskoda/models/health.py, myskoda/models/info.py, myskoda/models/maintenance.py, myskoda/models/position.py, myskoda/models/spin.py, myskoda/models/status.py, myskoda/models/trip_statistics.py, myskoda/models/user.py, myskoda/myskoda.py, myskoda/rest_api.py, tests/test_generated.py, tests/test_rest_api.py
I hit a wall in https://github.com/skodaconnect/homeassistant-myskoda/pull/632 trying to selectively exclude updates of the Vehicle.health based on the last timestamp:
When intentionally excluding specific capabilities (~endpoints) the
problem is that the corresponding Vehicle fields will be None in the
returned Vehicle.
So either the client/caller must have the knowledge of the
capability->endpoint->field mapping and stitch together the previous and
new Vehicle, or the MySkoda class must store the last Vehicle(s) and
update what can be updated. The second option seems much cleaner and
keeps internal logic encapsulated in the myskoda lib.
I've used the opportunity to refactor how the timestamp field is set. Rather than allowing it to be None and explicitly having to set it in the RestApi …
=> Cache and update the last Vehicle

myskoda/myskoda.py
Ensure a new Vehicle object is returned by
get_vehicle/get_partial_vehicle.
If the same object is always returned, even if the content changes, the HA Coordinator doesn't know there was an update and thus doesn't trigger the entity listeners.
Fixes https://github.com/skodaconnect/homeassistant-myskoda/issues/651
=> Force new Vehicle to be returned

myskoda/cli/mqtt.py, myskoda/mqtt.py, myskoda/myskoda.py, tests/test_mqtt.py
Just a minor type hinting fix I ran into while trying to understand something else, and learning more about async types.
`subscribe()` is passed an async function, which is callable returning a `Coroutine`, not an `Awaitable`, and definitely not `None`.
This then avoids the rogue cast to `Any` when passing the result of calling the callback function into `asyncio.create_task`.
=> Fix type hint for mqtt callbacks

myskoda/myskoda.py
This is annoying because access events seems to occur for about anything but at least position is something we need to refresh on access it seems. Departure events explicitly refresh position but those don't seem to occur reliably - or perhaps occur before the API knows the new position...
Note that a full refresh on access events is what we already had prior to moving event handling from the coordinator into the myskoda lib, so this is actually just reverting back to previous behavior.
Perhaps we'll find a better event to trigger a full refresh (or a position refresh).
=> Perform full vehicle refresh on access events

README.md
This commit fixes the error shown below when using the basic example from the README. 
> RuntimeWarning: coroutine 'MySkoda.disconnect' was never awaited
>   myskoda.disconnect()
> RuntimeWarning: Enable tracemalloc to get the object allocation traceback
=> Readme: Adding await to disconnect in basic example

myskoda/models/fixtures.py, myskoda/myskoda.py
When adding the vehicle_connection_status to the library, I forgot to add it to the fixtures as well, as discovered by a user on Discord in https://discord.com/channels/877164727636230184/877167631935897621/1371858211937845250
This adds the new status to fixtures as well
=> fix: add vehicle_connection_status to fixture generator

myskoda/myskoda.py
This improves API efficiency by only requesting readiness if the vehicle has the capability.
Refactor `_request_capability_data` to reduce complexity since `ruff` did not like the branch points anymore.
=> chore: add readiness as a seperate API call

myskoda/auth/authorization.py, myskoda/mqtt.py, myskoda/myskoda.py, pyproject.toml, tests/conftest.py, tests/test_mqtt.py, tests/test_operations.py, uv.lock
Allow tests injecting their own fake client so that we can test
`MySkodaMqttClient` without needing an actual MQTT broker.
Fixes #401.
amqtt is old, unmaintained, and causes dependency issues.
Rather than trying to replace it we've refactored the tests and tested
code to no longer depend on a 'real' MQTT broker running. This focuses
the tests on our own code instead of mostly testing the MQTT client lib
(`aiomqtt`).
This is done by injecting a fake `aiomqtt.Client` in `MySkodaMqttClient`.
The tests in `tests/test_operations.py` can probably be further simplified/de-duplicated but that will be for another day and not what I was going for here 😅 .
=> chore/refactor: remove amqtt, refactor tests + MySkodaMqttClient

myskoda/models/user.py
Ran across it while restarting the integration today.
Additionally:
- Sort the Enum alphabetically
- rename `drop_unknown_capabilities` to `drop_unknown_usercapabilities` to be more precise
=> fix: add missing LOYALTY_PROGRAM user capability

docs/api_endpoints.md, myskoda/cli/__init__.py, myskoda/cli/requests.py, myskoda/models/maintenance.py, myskoda/myskoda.py, myskoda/rest_api.py, myskoda/vehicle.py, tests/test_generated.py
After #446 the `maintenance` data we have available becomes more and more.
This implements the `maintenance_report`.
Think of the `maintenance_report` as a short summary of `maintenance`, coming from the `/v3/vehicle-maintenance/vehicles/{vin}/report` endpoint.
We can implement a different caching strategy here, since this part of the data is expected to change at least once per trip. Other data in the `maintenance` endpoint is expected to be more static than this and certainly doesn't need to be refreshed more than once in 24h
=> feat: add the maintenance-report, summary of maintenance from a different endpoint

myskoda/mqtt.py, myskoda/myskoda.py
Used to be the case but was accidentally dropped when migrating to aiomqtt.
=> fix: pass the HA ssl_context into the mqtt client

myskoda/myskoda.py
This lets Odometer related events update onlye the `maintenance_report` instead of the full `maintenance`, since this contains largely static data.
Additionally, this drops updating basic car `Info` upon Odometer event, since `Info` contains no Odometer related information.
=> chore: use maintenance_report method upon odometer update

myskoda/mqtt.py
As per https://docs.python.org/3/library/ssl.html#ssl.PROTOCOL_TLS:
`Deprecated since version 3.10: TLS clients and servers require different default settings for secure communication. The generic TLS protocol constant is deprecated in favor of [PROTOCOL_TLS_CLIENT](https://docs.python.org/3/library/ssl.html#ssl.PROTOCOL_TLS_CLIENT) and [PROTOCOL_TLS_SERVER](https://docs.python.org/3/library/ssl.html#ssl.PROTOCOL_TLS_SERVER).
`
We require python3.13 these days for this library, so should be safe to update to the newer constant.
Tested in my deployment
=> fix: replace deprecated PROTOCOL_TLS with PROTOCOL_TLS_CLIENT

myskoda/models/event/vehicle.py
As reported in skodaconnect/homeassistant-myskoda#899, the addition of `vehicle-connection-offline` in #464 was incomplete.
This PR adds the missing `dataclass`
=> fix: add dataclass for vehicle-connection-offline message
